# kAFL configuration
qemu_path: $QEMU_ROOT/x86_64-softmmu/qemu-system-x86_64
ptdump_path: $LIBXDC_ROOT/build/ptdump_static
radamsa_path: $RADAMSA_ROOT/bin/radamsa

# base qemu config
qemu_base: -enable-kvm -machine kAFL64-v1 -cpu kAFL64-Hypervisor-v1,+vmx -no-reboot -display none -netdev user,id=mynet0 -device virtio-net,netdev=mynet0
qemu_extra:

# linux cmdline - hprintf=7 enables verbose printk logging
#qemu_append: root=/dev/vda1 rw hprintf=7 nokaslr oops=panic nopti mitigations=off
qemu_append: root=/dev/vda1 rw hprintf=4 nokaslr oops=panic nopti mitigations=off
